[package]
name = "typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22"
crossbeam = "0.8.0"
clap = "3.0.14"
lipsum = "0.8"
rand = "0.8.5"
